/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bonoloto;

/**
 *
 * @author Brais Núñez
 */
public class Ventana extends javax.swing.JFrame {
     
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        this.setTitle("                                                                                                          jLotto");          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        txtNum4 = new javax.swing.JTextField();
        botonJugar = new javax.swing.JButton();
        txtNum2 = new javax.swing.JTextField();
        txtNum5 = new javax.swing.JTextField();
        txtNum3 = new javax.swing.JTextField();
        txtNum6 = new javax.swing.JTextField();
        txtNum1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        etiquetaFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNum4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelFondo.add(txtNum4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 30, -1));

        botonJugar.setBackground(new java.awt.Color(0, 0, 0));
        botonJugar.setForeground(new java.awt.Color(255, 255, 255));
        botonJugar.setText("JUGAR");
        botonJugar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonJugarActionPerformed(evt);
            }
        });
        panelFondo.add(botonJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 90, 60));

        txtNum2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelFondo.add(txtNum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 30, -1));

        txtNum5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelFondo.add(txtNum5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 30, -1));

        txtNum3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelFondo.add(txtNum3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 30, -1));

        txtNum6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelFondo.add(txtNum6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, 30, -1));

        txtNum1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNum1ActionPerformed(evt);
            }
        });
        panelFondo.add(txtNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 30, -1));

        jLabel1.setFont(new java.awt.Font("Rage Italic", 1, 24)); // NOI18N
        jLabel1.setText("Escoja 6 números");
        panelFondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 180, 30));

        etiquetaFondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Brais Núñez\\Desktop\\Desarrollo de aplicaciones multiplataforma\\Programacion\\3ªEvaluacion\\Bonoloto\\src\\shiny-lottery-balls.jpg")); // NOI18N
        panelFondo.add(etiquetaFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 0, 1010, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public String [] numEsc = new String[6];
    
    public String[] cargarNumEsc(){
        
        numEsc[0] = txtNum1.getText();
        numEsc[1] = txtNum2.getText();
        numEsc[2] = txtNum3.getText();
        numEsc[3] = txtNum4.getText();
        numEsc[4] = txtNum5.getText();
        numEsc[5] = txtNum6.getText();
        
        return numEsc;
              
    }
    
    private void txtNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNum1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNum1ActionPerformed

    private void botonJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonJugarActionPerformed
        
        cargarNumEsc();
        Ventana2 ven2 = new Ventana2();
        ven2.setVisible(true);
        ven2.setLocationRelativeTo(null);
        visualizarNumEsc();
        this.setVisible(false);
        
    }//GEN-LAST:event_botonJugarActionPerformed

    public void visualizarNumEsc(){
        
        for(int i=0; i<numEsc.length; i++){
            System.out.println(numEsc[i]);
            
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonJugar;
    private javax.swing.JLabel etiquetaFondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JTextField txtNum1;
    private javax.swing.JTextField txtNum2;
    private javax.swing.JTextField txtNum3;
    private javax.swing.JTextField txtNum4;
    private javax.swing.JTextField txtNum5;
    private javax.swing.JTextField txtNum6;
    // End of variables declaration//GEN-END:variables
}
