/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bonoloto;

/**
 *
 * @author Brais Núñez
 */
public class Ventana2 extends javax.swing.JFrame {
    
    Ventana ventana1 = new Ventana();
    String [] aux = new String[5];
    
    
    
    /**
     * Creates new form Ventana2
     */
    public Ventana2() {
        initComponents();
        aux = ventana1.cargarNumEsc();
        visualizarAux();
        cargarEtiquetaEsc();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        etiquetaSuperior = new javax.swing.JLabel();
        etiquetaNum1 = new javax.swing.JLabel();
        etiquetaNum2 = new javax.swing.JLabel();
        etiquetaNum3 = new javax.swing.JLabel();
        etiquetaNum4 = new javax.swing.JLabel();
        etiquetaNum5 = new javax.swing.JLabel();
        etiquetaNum6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        etiquetaEsc2 = new javax.swing.JLabel();
        etiquetaEsc3 = new javax.swing.JLabel();
        etiquetaEsc4 = new javax.swing.JLabel();
        etiquetaEsc5 = new javax.swing.JLabel();
        etiquetaEsc6 = new javax.swing.JLabel();
        etiquetaEsc1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaSuperior.setFont(new java.awt.Font("Rage Italic", 1, 36)); // NOI18N
        etiquetaSuperior.setText("Los números agraciados han sido");
        jPanel1.add(etiquetaSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 500, 30));

        etiquetaNum1.setText("jLabel2");
        jPanel1.add(etiquetaNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 40, 30));

        etiquetaNum2.setText("jLabel2");
        jPanel1.add(etiquetaNum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 40, 30));

        etiquetaNum3.setText("jLabel2");
        jPanel1.add(etiquetaNum3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 40, 30));

        etiquetaNum4.setText("jLabel2");
        jPanel1.add(etiquetaNum4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 40, 30));

        etiquetaNum5.setText("jLabel2");
        jPanel1.add(etiquetaNum5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 40, 30));

        etiquetaNum6.setText("jLabel2");
        jPanel1.add(etiquetaNum6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 40, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 480, 10));

        jLabel2.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        jLabel2.setText("Sus números escogidos fueron");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, 40));

        etiquetaEsc2.setText("jLabel3");
        jPanel1.add(etiquetaEsc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        etiquetaEsc3.setText("jLabel3");
        jPanel1.add(etiquetaEsc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));

        etiquetaEsc4.setText("jLabel3");
        jPanel1.add(etiquetaEsc4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        etiquetaEsc5.setText("jLabel3");
        jPanel1.add(etiquetaEsc5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        etiquetaEsc6.setText("jLabel3");
        jPanel1.add(etiquetaEsc6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));

        etiquetaEsc1.setText("jLabel3");
        jPanel1.add(etiquetaEsc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Brais Núñez\\Desktop\\Desarrollo de aplicaciones multiplataforma\\Programacion\\3ªEvaluacion\\Bonoloto\\src\\fondo2.jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void visualizarAux(){
        for(int i=0; i<ventana1.numEsc.length; i++){
            System.out.println("----" + ventana1.numEsc[i]);
            
        }
        
    }
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void cargarEtiquetaEsc(){
        
       
       
       
        
        etiquetaEsc1.setText(aux[0]);
        etiquetaEsc2.setText(aux[1]);
        etiquetaEsc3.setText(aux[2]);
        etiquetaEsc4.setText(aux[3]);
        etiquetaEsc5.setText(aux[4]);
        etiquetaEsc6.setText(aux[5]); 
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana2().setVisible(true);                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etiquetaEsc1;
    private javax.swing.JLabel etiquetaEsc2;
    private javax.swing.JLabel etiquetaEsc3;
    private javax.swing.JLabel etiquetaEsc4;
    private javax.swing.JLabel etiquetaEsc5;
    private javax.swing.JLabel etiquetaEsc6;
    private javax.swing.JLabel etiquetaNum1;
    private javax.swing.JLabel etiquetaNum2;
    private javax.swing.JLabel etiquetaNum3;
    private javax.swing.JLabel etiquetaNum4;
    private javax.swing.JLabel etiquetaNum5;
    private javax.swing.JLabel etiquetaNum6;
    private javax.swing.JLabel etiquetaSuperior;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
